version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ../config/.cache/database/:/var/lib/mysql
      - ../config/dumps/:/dumps
      - ./config/mysql/:/config
